// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v5.29.3
// source: common/common.proto

/* eslint-disable */

export const protobufPackage = "common";

/**  */
export interface Empty {
}

export interface GetRequest {
  id: string;
}

export interface Response {
  status: number;
  success: boolean;
  message: string;
  data: { [key: string]: string };
  error?: string | undefined;
}

export interface Response_DataEntry {
  key: string;
  value: string;
}

export interface ListResponse {
  status: number;
  success: boolean;
  message: string;
  error?: string | undefined;
  data: ListResponse_List[];
}

export interface ListResponse_List {
  data: { [key: string]: string };
}

export interface ListResponse_List_DataEntry {
  key: string;
  value: string;
}

export const COMMON_PACKAGE_NAME = "common";
